version: '2'
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - funcorder
    - noinlineerr
  exclusions:
    rules:
      - linters:
          - err113
          - funlen
          - staticcheck
          - testpackage
        path: (.+)_test\.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
